import { NextResponse } from 'next/server';

export async function GET() {
  const data = {
    brands: ['Chevrolet', 'BYD', 'Kia', 'Hyundai', 'Chery', 'HAVAL', 'Jetour', 'Bestune', 'Leapmotors', 'Lada', 'Volkswagen', 'Daewoo', 'Toyota', 'Mersedes', 'BMW', 'Boshqa'],
    catalog: {
      'Chevrolet': {
        'matiz': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 120000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 40000 },
          { "name": "🌀 Drosil tozalash", "price": 50000 },
          { "name": "💉 Injector tozalash", "price": 70000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 200000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 50000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'tico': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 120000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 40000 },
          { "name": "🌀 Drosil tozalash", "price": 50000 },
          { "name": "💉 Injector tozalash", "price": 70000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 200000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 50000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'damas': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 100000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 40000 },
          { "name": "🌀 Drosil tozalash", "price": 50000 },
          { "name": "💉 Injector tozalash", "price": 70000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 200000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 70000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'nexia 1': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 120000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 40000 },
          { "name": "🌀 Drosil tozalash", "price": 50000 },
          { "name": "💉 Injector tozalash", "price": 70000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 200000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 50000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'nexia 2': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 120000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 40000 },
          { "name": "🌀 Drosil tozalash", "price": 50000 },
          { "name": "💉 Injector tozalash", "price": 70000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 200000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 50000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'nexia 3': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 150000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 50000 },
          { "name": "🌀 Drosil tozalash", "price": 50000 },
          { "name": "💉 Injector tozalash", "price": 70000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 200000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 50000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'lasseti': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 120000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 50000 },
          { "name": "🌀 Drosil tozalash", "price": 50000 },
          { "name": "💉 Injector tozalash", "price": 70000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 200000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 50000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'spark': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 150000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 50000 },
          { "name": "🌀 Drosil tozalash", "price": 50000 },
          { "name": "💉 Injector tozalash", "price": 100000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 200000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 50000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'captiva 1, 2, 3': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 500000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 100000 },
          { "name": "🌀 Drosil tozalash", "price": 100000 },
          { "name": "💉 Injector tozalash", "price": 400000 },
          { "name": "🛣️ Probeg tekshirish", "price": 200000 },
          { "name": "💻 Programma yozish", "price": 300000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 100000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'captiva 4': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 300000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 100000 },
          { "name": "🌀 Drosil tozalash", "price": 100000 },
          { "name": "💉 Injector tozalash", "price": 400000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 400000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 100000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'captiva 5': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 400000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 100000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 100000 },
          { "name": "🌀 Drosil tozalash", "price": 100000 },
          { "name": "💉 Injector tozalash", "price": 200000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 800000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 80000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 100000 }
        ],
        'gentra': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 120000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 40000 },
          { "name": "🌀 Drosil tozalash", "price": 50000 },
          { "name": "💉 Injector tozalash", "price": 70000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 200000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 50000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'cruze': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 120000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 50000 },
          { "name": "🌀 Drosil tozalash", "price": 50000 },
          { "name": "💉 Injector tozalash", "price": 70000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 200000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 70000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 100000 }
        ],
        'cobalt': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 400000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 50000 },
          { "name": "🌀 Drosil tozalash", "price": 50000 },
          { "name": "💉 Injector tozalash", "price": 80000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 200000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 200000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'epica': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 500000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 200000 },
          { "name": "🌀 Drosil tozalash", "price": 100000 },
          { "name": "💉 Injector tozalash", "price": 250000 },
          { "name": "🛣️ Probeg tekshirish", "price": 50000 },
          { "name": "💻 Programma yozish", "price": 300000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 80000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'onix': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 400000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 50000 },
          { "name": "🌀 Drosil tozalash", "price": 80000 },
          { "name": "💉 Injector tozalash", "price": 70000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 200000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 250000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 }
        ],
        'malibu 1': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 250000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 50000 },
          { "name": "🌀 Drosil tozalash", "price": 80000 },
          { "name": "💉 Injector tozalash", "price": 150000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 200000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 80000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 100000 }
        ],
        'malibu 2 /primer': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 900000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 100000 },
          { "name": "🌀 Drosil tozalash", "price": 80000 },
          { "name": "💉 Injector tozalash", "price": 600000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 600000 },
          { "name": "🚀 Stage urish", "price": 800000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 250000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 100000 }
        ],
        'malibu 2.4': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 500000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 100000 },
          { "name": "🌀 Drosil tozalash", "price": 80000 },
          { "name": "💉 Injector tozalash", "price": 300000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 400000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 250000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 200000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 100000 }
        ],
        'tracker 1': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 500000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 50000 },
          { "name": "🌀 Drosil tozalash", "price": 70000 },
          { "name": "💉 Injector tozalash", "price": 100000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 400000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 300000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 100000 }
        ],
        'tracker 2': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 500000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 50000 },
          { "name": "🌀 Drosil tozalash", "price": 70000 },
          { "name": "💉 Injector tozalash", "price": 100000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 400000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 300000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 100000 }
        ],
        'equinox 1': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 1000000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 100000 },
          { "name": "🌀 Drosil tozalash", "price": 100000 },
          { "name": "💉 Injector tozalash", "price": 600000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 600000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 400000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 600000 }
        ],
        'equinox 2': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 1000000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 100000 },
          { "name": "🌀 Drosil tozalash", "price": 100000 },
          { "name": "💉 Injector tozalash", "price": 600000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 600000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 400000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 600000 }
        ],
        'orlando 1, 2': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 500000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 50000 },
          { "name": "🌀 Drosil tozalash", "price": 70000 },
          { "name": "💉 Injector tozalash", "price": 100000 },
          { "name": "🛣️ Probeg tekshirish", "price": 50000 },
          { "name": "💻 Programma yozish", "price": 400000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 300000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 100000 }
        ],
        'monza 1.3 , 1.5': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 400000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 50000 },
          { "name": "🌀 Drosil tozalash", "price": 80000 },
          { "name": "💉 Injector tozalash", "price": 800000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 500000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 250000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 400000 }
        ],
        'traverse 1': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 1000000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 100000 },
          { "name": "🌀 Drosil tozalash", "price": 100000 },
          { "name": "💉 Injector tozalash", "price": 600000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 800000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 100000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 500000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 200000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 600000 }
        ],
        'traverse 2': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 1000000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 100000 },
          { "name": "🌀 Drosil tozalash", "price": 100000 },
          { "name": "💉 Injector tozalash", "price": 600000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 800000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 100000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 500000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 200000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 600000 }
        ],
        'tahoe 1': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 1000000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 100000 },
          { "name": "🌀 Drosil tozalash", "price": 100000 },
          { "name": "💉 Injector tozalash", "price": 600000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 800000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 100000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 500000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 200000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 600000 }
        ],
        'tahoe 2': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 1000000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 100000 },
          { "name": "🌀 Drosil tozalash", "price": 100000 },
          { "name": "💉 Injector tozalash", "price": 600000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 800000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 100000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 500000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 200000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 600000 }
        ],
        'trailblazer': [
          { "name": "🔍 Diagnostika", "price": 50000 },
          { "name": "⛽ Benzin sistemasini ko'rish", "price": 1000000 },
          { "name": "🚫 Tabloda datchik o'chirish", "price": 50000 },
          { "name": "🕯️ Svechalarni almashtirish", "price": 100000 },
          { "name": "🌀 Drosil tozalash", "price": 100000 },
          { "name": "💉 Injector tozalash", "price": 600000 },
          { "name": "🛣️ Probeg tekshirish", "price": 100000 },
          { "name": "💻 Programma yozish", "price": 600000 },
          { "name": "🚀 Stage urish", "price": 600000 },
          { "name": "⛽ Gaz regulirovka", "price": 50000 },
          { "name": "⛽ Benzin nasos ko'rish", "price": 400000 },
          { "name": "🧵 Simlarni to'g'irlash", "price": 100000 },
          { "name": "🇷🇺 Russifikatsiya (Rus tilida qilish)", "price": 150000 },
          { "name": "📱 Prilojeniye (Ilovalar) o'rnatish", "price": 600000 }
        ],
      },
      'Hyundai': {
        'Elantra': [], 'Sonata': [], 'Tucson': [], 'Santa Fe': [], 'Palisade': []
      },
      'Kia': {
        'K5': [], 'Sorento': [], 'Sportage': [], 'Carnival': [], 'Seltos': []
      },
      'BYD': {
        'Song Plus': [], 'Han': [], 'Chazor': []
      },
      'Chery': {},
      'HAVAL': {},
      'Jetour': {},
      'Bestune': {},
      'Leapmotors': {},
      'Lada': {},
      'Volkswagen': {},
      'Boshqa': {}
    }
  };
  
  return NextResponse.json(data);
}
