-- Audit log jadvali — kim, qachon, nimani o'zgartirgani
-- Supabase SQL Editor'da bir marta ishga tushiring.

create table if not exists public.audit_log (
  id          bigint generated by default as identity primary key,
  action      text not null,                    -- create | update | delete | payment | ...
  entity      text not null,                    -- order | operation | salary | client | ...
  entity_id   text,                             -- tegishli yozuv IDsi
  user_role   text,                             -- egasi | sherik | xodim
  user_name   text,                             -- foydalanuvchi nomi
  details     jsonb,                            -- qo'shimcha ma'lumot (eski/yangi qiymatlar)
  created_at  timestamptz not null default now()
);

create index if not exists audit_log_created_at_idx on public.audit_log (created_at desc);
create index if not exists audit_log_entity_idx     on public.audit_log (entity, entity_id);
