-- Mashina klassi koeffitsienti — qimmat avtomobil va elektromobil ishi
-- odatdagi mashinadan uzoqroq davom etadi.
--
-- Nega koeffitsient, har markaga alohida norma emas: 127 xizmat x 44 marka =
-- 5588 qator bo'lardi. Koeffitsient bilan bitta bazaviy norma yoziladi, marka
-- esa uni kerakli darajada kengaytiradi.
--
-- Yakuniy norma = bazaviy norma x koeffitsient. Agar service_norms'da o'sha
-- marka/model uchun ANIQ norma yozilgan bo'lsa, u to'g'ridan-to'g'ri ishlatiladi
-- (koeffitsient qo'llanmaydi — aniq qiymat allaqachon shu mashina uchun).
--
-- brand_norm/car_model_norm — kichik harf, harf-raqamdan boshqasi olib tashlangan.
-- Bazada bir marka turlicha yozilgan: "BYD"/"Byd", "Mercedes-Benz"/"MERCEDESBENZ".
--
-- Qo'lda Supabase SQL editorda ishga tushiriladi (db/points_system.sql kabi).

create table if not exists public.car_classes (
  id             bigint generated by default as identity primary key,
  brand_norm     text not null,
  car_model_norm text,                  -- null = butun marka uchun
  brand_asl      text,                  -- egasi ko'rishi uchun asl yozilishi
  car_model_asl  text,
  klass          text not null,         -- 'oddiy' | 'orta' | 'elektro' | 'premium'
  koeffitsient   numeric(4,2) not null check (koeffitsient > 0 and koeffitsient <= 5),
  izoh           text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create unique index if not exists car_classes_key_uq
  on public.car_classes (brand_norm, coalesce(car_model_norm, ''));
create index if not exists car_classes_brand_idx on public.car_classes (brand_norm);

alter table public.car_classes enable row level security;
