INSERT INTO cars_list (name, brand)
VALUES
('Song Plus', 'BYD'),
('Song plus gibrid', 'BYD'),
('chempion gibrid', 'BYD'),
('Chazor', 'BYD'),
('Seal', 'BYD'),
('Xan gibrid', 'BYD'),
('Song Pro', 'BYD'),
('Seagull', 'BYD'),
('Tang', 'BYD'),
('Yuan', 'BYD'),
('Yuan up', 'BYD'),
('Yuan up gibrid', 'BYD'),
('Carnival', 'Kia'),
('Bongo', 'Kia'),
('Bongo EV', 'Kia'),
('EV 3', 'Kia'),
('EV 5', 'Kia'),
('EV 6', 'Kia'),
('EV 9', 'Kia'),
('K 3', 'Kia'),
('K 5', 'Kia'),
('K 8', 'Kia'),
('K 8 restaylin', 'Kia'),
('K 9', 'Kia'),
('Morning', 'Kia'),
('Seltos', 'Kia'),
('Sorento', 'Kia'),
('Sportage', 'Kia'),
('Elantra', 'Hyundai'),
('creta', 'Hyundai'),
('Ioniq5', 'Hyundai'),
('Ioniq6', 'Hyundai'),
('Ioniq9', 'Hyundai'),
('Palisade', 'Hyundai'),
('Porter', 'Hyundai'),
('Santa fe', 'Hyundai'),
('Sonata', 'Hyundai'),
('Sonata 2008', 'Hyundai'),
('Staria', 'Hyundai'),
('Starex', 'Hyundai'),
('Tranjet', 'Hyundai'),
('arizo 6 pro', 'Chery'),
('arizo 7 pro', 'Chery'),
('tiggo 2', 'Chery'),
('tiggo 6 pro', 'Chery'),
('tiggo 7 pro', 'Chery'),
('tiggo 8 pro', 'Chery'),
('M6', 'HAVAL'),
('H6', 'HAVAL'),
('JOLION', 'HAVAL'),
('DARGO', 'HAVAL'),
('X 70', 'Jetour'),
('X90', 'Jetour'),
('X95', 'Jetour'),
('DASHING', 'Jetour'),
('T 33', 'Bestune'),
('T 55', 'Bestune'),
('T 77', 'Bestune'),
('T 99', 'Bestune'),
('B 70', 'Bestune'),
('C 01', 'Leapmotors'),
('C 10', 'Leapmotors'),
('C 11', 'Leapmotors'),
('C 16', 'Leapmotors'),
('vesta', 'Lada'),
('X ray', 'Lada'),
('gazel', 'Lada'),
('granta', 'Lada'),
('ID 3', 'Volkswagen'),
('ID 4', 'Volkswagen'),
('ID 6', 'Volkswagen'),
('CADDY', 'Volkswagen'),
('LI 6', 'Li auto'),
('LI 7', 'Li auto'),
('LI 8', 'Li auto'),
('LI 9', 'Li auto'),
('LI 9 Restaling', 'Li auto'),
('matiz', 'Chevrolet'),
('tico', 'Chevrolet'),
('damas', 'Chevrolet'),
('nexia 1', 'Chevrolet'),
('nexia 2', 'Chevrolet'),
('nexia 3', 'Chevrolet'),
('lasseti', 'Chevrolet'),
('spark', 'Chevrolet'),
('captiva 1, 2, 3,', 'Chevrolet'),
('captiva 4', 'Chevrolet'),
('captiva 5', 'Chevrolet'),
('gentra', 'Chevrolet'),
('cruze', 'Chevrolet'),
('cobalt', 'Chevrolet'),
('epica', 'Chevrolet'),
('onix', 'Chevrolet'),
('malibu 1', 'Chevrolet'),
('malibu 2', 'Chevrolet'),
('malibu 2.4', 'Chevrolet'),
('tracker 1', 'Chevrolet'),
('tracker 2', 'Chevrolet'),
('equinox 1', 'Chevrolet'),
('equinox 2', 'Chevrolet'),
('orlando 1, 2', 'Chevrolet'),
('monza 1.3 , 1.5', 'Chevrolet'),
('traverse 1', 'Chevrolet'),
('traverse 2', 'Chevrolet'),
('tahoe 1', 'Chevrolet'),
('tahoe 2', 'Chevrolet'),
('trailblazer', 'Chevrolet'),
('Jac J7', 'Boshqa'),
('Jac M4', 'Boshqa'),
('Deepal S7', 'Boshqa'),
('Foton', 'Boshqa'),
('Skoda Kodiq', 'Boshqa'),
('Im Motors L7', 'Boshqa'),
('Nissan Altima', 'Boshqa'),
('Range Rover Velar', 'Boshqa'),
('Wuling Baojun', 'Boshqa'),
('Hongqi HS7', 'Boshqa'),
('Jaguar', 'Boshqa'),
('Porsche Taycan', 'Boshqa'),
('Dong Feng 008', 'Boshqa'),
('Shineray T30', 'Boshqa'),
('I Car 03', 'Boshqa'),
('Denza N9', 'Boshqa'),
('Lynk & Co 900', 'Boshqa'),
('Mazda 6', 'Boshqa'),
('Dong Feng Aeolus', 'Boshqa')
ON CONFLICT (name) DO NOTHING;