-- Xodimlar uchun avtomatik ball/bonus tizimi — ball lentasi (audit-trail, pul emas).
-- Har bir (buyurtma xizmat qatori x mezon) uchun bitta o'zgarmas yozuv.
-- Qo'lda Supabase SQL editorda ishga tushiriladi (db/lifecycle_tracking.sql, db/audit_log.sql kabi).

create table if not exists public.points_ledger (
  id                  bigint generated by default as identity primary key,
  worker_id           bigint not null references workers(id) on delete cascade,
  order_id            bigint not null references orders(id) on delete cascade,
  service_index       int not null,
  service_catalog_id  bigint,
  service_nom         text,
  category            text not null check (category in ('speed','quality')),
  points              numeric not null,
  reason              text not null,
  detail              jsonb,
  period              text not null,
  payout_salary_id    bigint references salaries(id) on delete set null,
  computed_at         timestamptz not null default now(),
  created_at          timestamptz not null default now()
);

create unique index if not exists points_ledger_line_category_uq
  on points_ledger (order_id, service_index, category);
create index if not exists points_ledger_worker_period_idx on points_ledger (worker_id, period);
create index if not exists points_ledger_unpaid_idx on points_ledger (worker_id, period) where payout_salary_id is null;

alter table public.points_ledger enable row level security;
