-- ─────────────────────────────────────────────────────────────────────────────
-- RASXOD DAFTARI (rasxod_cars + rasxod_items) — /reports/rasxod
-- ─────────────────────────────────────────────────────────────────────────────
-- Mashinaga qilingan, lekin KASSADAN AYIRILMAGAN xarajatlar daftari:
-- mashina kartochkasi (rasxod_cars) + uning xarajat qatorlari (rasxod_items).
-- Mijoz pulni qaytarganda qator "to'landi" deb belgilanadi.
--
-- KASSAGA TEGMAYDI: `kassa`/`operations` bilan hech qanday bog'liqlik yo'q —
-- na rasxod yozilganda, na "to'landi" qilinganda pul harakati yoziladi.
-- Bot orqali kiritiladigan rasxoddan (orders.zaps, kassadan darrov ayiriladi)
-- butunlay alohida.
--
-- Kirish: faqat server API route'lari orqali (service_role, RLS'ni chetlab
-- o'tadi) — boshqa jadvallar kabi RLS yoqilgan, siyosat qo'shilmaydi.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.rasxod_cars (
  id         bigint generated by default as identity primary key,
  mashina    text not null default '',   -- model (masalan Chevrolet Malibu)
  raqam      text,                       -- davlat raqami
  mijoz      text,                       -- mijoz ismi
  tel        text,                       -- mijoz telefoni
  izoh       text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rasxod_items (
  id              bigint generated by default as identity primary key,
  car_id          bigint not null references public.rasxod_cars (id) on delete cascade,
  nom             text not null default '',           -- nima uchun (masalan Akkumulyator)
  summa           numeric not null check (summa > 0), -- so'm
  sana            date not null default ((now() at time zone 'Asia/Tashkent')::date),
  tulandi         boolean not null default false,     -- mijoz pulni TO'LIQ qaytardimi
  tulangan_summa  numeric not null default 0           -- qisman to'lov: hozirgacha qaytgan qism
                    check (tulangan_summa >= 0 and tulangan_summa <= summa),
  tulangan_vaqt   timestamptz,                         -- oxirgi to'lov (to'liq yoki qisman) vaqti
  created_at      timestamptz not null default now()
);

alter table public.rasxod_cars  enable row level security;
alter table public.rasxod_items enable row level security;

create index if not exists rasxod_items_car_id_idx on public.rasxod_items (car_id);
