-- Xizmat vaqt normalari — "injektor tozalash 1 soat", "svecha almashtirish 20 daqiqa".
-- Tezlik bahosi shu normaga qarab beriladi (db/points_system.sql bilan birga ishlaydi).
--
-- Nega alohida jadval, services_list'ga ustun emas: services_list'da 4239 qator bor
-- (350 mashina modeli x ~25 xizmat), lekin turli xizmat NOMI atigi ~25 ta. Normani
-- normallashtirilgan nomga bog'lash egasiga 4239 emas, ~25 ta qiymat kiritish
-- imkonini beradi. Kerak bo'lsa brand/model bo'yicha alohida istisno qo'shiladi.
--
-- Qo'lda Supabase SQL editorda ishga tushiriladi (db/points_system.sql kabi).

create table if not exists public.service_norms (
  id            bigint generated by default as identity primary key,
  nom_norm      text not null,          -- normallashtirilgan nom (kichik harf, emojisiz)
  nom_asl       text,                   -- egasi ko'rishi uchun asl yozilishi
  brand         text,                   -- null = barcha markalar uchun
  car_model     text,                   -- null = barcha modellar uchun
  norma_daqiqa  int not null check (norma_daqiqa > 0),
  izoh          text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Bitta (nom, brand, model) uchun bitta norma. coalesce — null'larni ham qamrab oladi.
create unique index if not exists service_norms_key_uq
  on public.service_norms (nom_norm, coalesce(brand, ''), coalesce(car_model, ''));
create index if not exists service_norms_nom_idx on public.service_norms (nom_norm);

alter table public.service_norms enable row level security;
