-- ─────────────────────────────────────────────────────────────────────────────
-- ZAPCHASTLAR KATALOGI (spare_parts)
-- ─────────────────────────────────────────────────────────────────────────────
-- Bu jadval OMBOR (`parts`) dan ALOHIDA. `parts` — narx/qoldiq bilan ombor
-- boshqaruvi. `spare_parts` — vizual ma'lumotnoma: zapchast rasmi + detal nomeri
-- (artikul) + qaysi mashinaga tegishli.
--
-- Kirish: barcha o'qish/yozish server API route'lari orqali (service_role bilan,
-- RLS'ni chetlab o'tadi) — boshqa jadvallar kabi. Shuning uchun RLS yoqilgan,
-- alohida siyosat qo'shilmaydi.
--
-- Rasmlar: `part-images` public storage bucket'da saqlanadi; jadvalda faqat
-- ommaviy URL massivi (`rasmlar`) turadi.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.spare_parts (
  id         bigint generated by default as identity primary key,
  nom        text not null default '',              -- zapchast nomi
  artikul    text,                                  -- detal nomeri (part number)
  brand      text,                                  -- mashina brendi (masalan Chevrolet)
  mashina    text default 'UMUMIY',                 -- model yoki UMUMIY
  rasmlar    jsonb not null default '[]'::jsonb,     -- rasm URL massivi
  izoh       text,                                  -- qo'shimcha izoh
  narx       numeric,                               -- zapchast narxi (so'm), ixtiyoriy
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.spare_parts enable row level security;

create index if not exists spare_parts_artikul_idx on public.spare_parts (artikul);
create index if not exists spare_parts_mashina_idx on public.spare_parts (mashina);
create index if not exists spare_parts_brand_idx   on public.spare_parts (brand);

-- Rasmlar uchun ommaviy (public) storage bucket.
insert into storage.buckets (id, name, public)
values ('part-images', 'part-images', true)
on conflict (id) do nothing;
