-- Ish sessiyalari — xodim botda "Ishni boshladim"/"Tugatdim" bosganda yoziladi.
--
-- Nega kerak: qabul_vaqti→tayyor_vaqti mashina HOVLIDA TURGAN vaqtni o'lchaydi,
-- xodimning ishlagan vaqtini emas. Butun tarix bo'yicha sinaganda shu sabab
-- baholangan 4 ta buyurtmaning 4 tasi ham jarima chiqdi (bitta ham bonus yo'q) —
-- normalar sof ish vaqtiga, o'lchov esa navbat+ish vaqtiga tayangani uchun.
-- Sessiya bilan tezlik bali aynan kalit burash vaqtiga bog'lanadi.
--
-- Bitta buyurtmada bir necha sessiya bo'lishi mumkin (tushlik, zapchast kutish,
-- ertaga davom ettirish) — jami ularning yig'indisi.
--
-- Qo'lda Supabase SQL editorda ishga tushiriladi (db/points_system.sql kabi).

create table if not exists public.work_sessions (
  id          bigint generated by default as identity primary key,
  order_id    bigint not null references orders(id) on delete cascade,
  worker_id   bigint not null references workers(id) on delete cascade,
  started_at  timestamptz not null default now(),
  ended_at    timestamptz,
  auto_closed boolean not null default false,  -- xodim "tugatdim" bosmagan, tizim yopgan
  created_at  timestamptz not null default now()
);

create index if not exists work_sessions_order_idx on public.work_sessions (order_id);
create index if not exists work_sessions_worker_idx on public.work_sessions (worker_id);

-- Bitta xodim bitta buyurtmada bir vaqtda faqat BITTA ochiq sessiyaga ega bo'ladi
-- (tugmani ikki marta bosish yangi sessiya ochib yubormasin).
create unique index if not exists work_sessions_open_uq
  on public.work_sessions (order_id, worker_id) where ended_at is null;

alter table public.work_sessions enable row level security;
