-- ─────────────────────────────────────────────────────────────────────────────
-- ZAP_ARCHIVE — buyurtmadan olib tashlangan zapchast qatorlari (doimiy tarix)
-- ─────────────────────────────────────────────────────────────────────────────
-- /parts/reports (Zapchastlar hisoboti) buyurtmalardagi `orders.zaps` dan
-- hosil bo'ladi. Buyurtma tahrirlanganda zapchast o'chirilsa (yoki buyurtmaning
-- o'zi o'chirilsa) qator `zaps`dan yo'qoladi — hisobotdan ham. Hisobot DOIMIY
-- bo'lishi uchun olib tashlangan har bir qator shu jadvalga NUSXALANADI va
-- hisobotda "olib tashlangan" belgisi bilan ko'rsatiladi.
--
-- order_id'da FK YO'Q: buyurtma o'chirilgandan keyin ham yozuv qolishi shart.
-- Jadval faqat QO'SHILADI (append-only) — ilova hech qachon UPDATE/DELETE qilmaydi.
-- Kassa/ombor bilan bog'liqligi yo'q: bu faqat ko'rish uchun tarix.
--
-- Kirish: faqat server API route'lari orqali (service_role, RLS'ni chetlab
-- o'tadi) — boshqa jadvallar kabi RLS yoqilgan, siyosat qo'shilmaydi.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.zap_archive (
  id           bigint generated by default as identity primary key,
  order_id     bigint not null,                 -- buyurtma raqami (buyurtma o'chirilgan bo'lsa ham qoladi)
  zap          jsonb  not null,                 -- olib tashlangan qatorning asl ko'rinishi (nom, narx, qty, rasxod, ...)
  mashina      text   not null default '',      -- olib tashlash paytidagi buyurtma ma'lumotlari (nusxa)
  raqam        text   not null default '',
  ism          text   not null default '',
  xodim        text   not null default '',      -- hisobotdagi "Xodim" ustuni (rasxod: kiritgan, oddiy: qabul qilgan)
  order_holat  text,                            -- olib tashlash paytidagi buyurtma holati
  sana         timestamptz,                     -- qator qo'shilgan vaqt (zap.vaqt, bo'lmasa buyurtma yaratilgan vaqt)
  sabab        text   not null check (sabab in ('tahrirlandi', 'buyurtma_ochirildi')),
  removed_at   timestamptz not null default now()
);

alter table public.zap_archive enable row level security;

create index if not exists zap_archive_order_id_idx   on public.zap_archive (order_id);
create index if not exists zap_archive_removed_at_idx on public.zap_archive (removed_at desc);
