-- ─────────────────────────────────────────────────────────────────────────────
-- ZAP_PULI_CHIQIM — "kassaga tushmagan zapchast puli" dan ayirilgan summalar
-- ─────────────────────────────────────────────────────────────────────────────
-- Buyurtmalarda "alohida" (galochka) belgilangan zapchastlarning puli KASSAGA
-- TUSHMAYDI — u alohida yig'ilib boradi va Ehtiyot qismlar sahifasidagi
-- bannerda ko'rsatiladi (yig'ilgan tushum + foyda).
--
-- Bu jadval — o'sha yig'ilgan puldan OLINGAN/ISHLATILGAN summalar (masalan
-- ta'minotchiga berildi). Banner qoldiqni ko'rsatadi:
--     qoldiq = yig'ilgan tushum − shu jadvaldagi chiqimlar
--
-- KASSAGA TEGMAYDI: `kassa`/`operations` bilan bog'liqligi yo'q — bu pul
-- kassada hech qachon bo'lmagan, shuning uchun kassa hisobotlariga ham
-- kirmaydi (rasxod_daftar bilan bir xil mantiq).
--
-- Foyda (narx − tannarx) ko'rsatkichi chiqimdan O'ZGARMAYDI: chiqim pulning
-- qayerga ketganini yozadi, zapchastdan topilgan foydani kamaytirmaydi.
--
-- Kirish: faqat server API route'lari orqali (service_role, RLS'ni chetlab
-- o'tadi) — boshqa jadvallar kabi RLS yoqilgan, siyosat qo'shilmaydi.
-- Yozish/o'chirish huquqi: hisobotlar bo'limiga ruxsati bor rollar
-- (egasi, boshliq, sherik) — qarang: src/app/api/parts/zap-pool.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.zap_puli_chiqim (
  id         bigint generated by default as identity primary key,
  summa      numeric not null check (summa > 0),   -- ayirilgan summa
  izoh       text    not null default '',          -- nimaga ishlatilgani
  sana       date    not null,                     -- Toshkent kuni (server qo'yadi)
  created_at timestamptz not null default now()
);

alter table public.zap_puli_chiqim enable row level security;

create index if not exists zap_puli_chiqim_created_at_idx on public.zap_puli_chiqim (created_at desc);
